name: strawberry_diagnosis
description: An app to upload strawberry images and diagnose diseases using AWS Amplify.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  amplify_flutter: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_storage_s3: ^2.6.1
  image_picker: ^1.1.2
  amplify_api: ^2.6.1
  file_picker: ^10.2.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_analytics: ^11.5.0
  cloud_firestore: ^5.6.9 
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/amplifyconfiguration.dart
    - images/logo.jpg
    - assets/images/hero_card_picture.jpg
    - assets/images/recent_scan_placeholder.jpg
    - assets/illustrations/undraw_no-data_ig65.svg


fonts:
    - family: DM Sans
      fonts:
        - asset: fonts/DM_Sans/static/DMSans-Regular.ttf
        - asset: fonts/DM_Sans/static/DMSans-Bold.ttf
          weight: 700