// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtFTgYl8IlVrxLYBDqcfhp7Bx23sTYfE',
    appId: '1:184330974752:web:eab3b4d2d5509a2f37ae45',
    messagingSenderId: '184330974752',
    projectId: 'hydrotex-auth',
    authDomain: 'hydrotex-auth.firebaseapp.com',
    storageBucket: 'hydrotex-auth.firebasestorage.app',
    measurementId: 'G-5HYK81FR0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZtnd3y1ZnV1R1OU5eYfOELmvF6BN1Aa0',
    appId: '1:184330974752:android:d17f60862cdeefbe37ae45',
    messagingSenderId: '184330974752',
    projectId: 'hydrotex-auth',
    storageBucket: 'hydrotex-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdv2zvjqTZ6b71sfAbZQbGxRn7S4RbyIA',
    appId: '1:184330974752:ios:9861439c7af7ff9b37ae45',
    messagingSenderId: '184330974752',
    projectId: 'hydrotex-auth',
    storageBucket: 'hydrotex-auth.firebasestorage.app',
    iosClientId: '184330974752-5h9jfga63a1j0hm2v9m5cmll5i9n1en5.apps.googleusercontent.com',
    iosBundleId: 'com.example.strawberryDiagnosis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdv2zvjqTZ6b71sfAbZQbGxRn7S4RbyIA',
    appId: '1:184330974752:ios:9861439c7af7ff9b37ae45',
    messagingSenderId: '184330974752',
    projectId: 'hydrotex-auth',
    storageBucket: 'hydrotex-auth.firebasestorage.app',
    iosClientId: '184330974752-5h9jfga63a1j0hm2v9m5cmll5i9n1en5.apps.googleusercontent.com',
    iosBundleId: 'com.example.strawberryDiagnosis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQtFTgYl8IlVrxLYBDqcfhp7Bx23sTYfE',
    appId: '1:184330974752:web:e54d257b8e50993537ae45',
    messagingSenderId: '184330974752',
    projectId: 'hydrotex-auth',
    authDomain: 'hydrotex-auth.firebaseapp.com',
    storageBucket: 'hydrotex-auth.firebasestorage.app',
    measurementId: 'G-63KD3YLDE4',
  );
}
