// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_AXOxArgta10S8CWalIHA96d1sLah8r0',
    appId: '1:1026608841497:web:3bc458ec5ace250a163b88',
    messagingSenderId: '1026608841497',
    projectId: 'plant-health-695dc',
    authDomain: 'plant-health-695dc.firebaseapp.com',
    storageBucket: 'plant-health-695dc.firebasestorage.app',
    measurementId: 'G-H43KNB75DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPf6aIGeaDpazVGLHAhWNKZ5FU0RIubAQ',
    appId: '1:1026608841497:android:59f0ed67f4a83ae2163b88',
    messagingSenderId: '1026608841497',
    projectId: 'plant-health-695dc',
    storageBucket: 'plant-health-695dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnr_oZlzw6lJm_PgXK0VlegxZfJqlfQ7E',
    appId: '1:1026608841497:ios:ea210a480e52685f163b88',
    messagingSenderId: '1026608841497',
    projectId: 'plant-health-695dc',
    storageBucket: 'plant-health-695dc.firebasestorage.app',
    iosBundleId: 'com.example.strawberryDiagnosis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnr_oZlzw6lJm_PgXK0VlegxZfJqlfQ7E',
    appId: '1:1026608841497:ios:ea210a480e52685f163b88',
    messagingSenderId: '1026608841497',
    projectId: 'plant-health-695dc',
    storageBucket: 'plant-health-695dc.firebasestorage.app',
    iosBundleId: 'com.example.strawberryDiagnosis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_AXOxArgta10S8CWalIHA96d1sLah8r0',
    appId: '1:1026608841497:web:202800f29df06e79163b88',
    messagingSenderId: '1026608841497',
    projectId: 'plant-health-695dc',
    authDomain: 'plant-health-695dc.firebaseapp.com',
    storageBucket: 'plant-health-695dc.firebasestorage.app',
    measurementId: 'G-NG5DKGK2FX',
  );
}
